version: "3"
services:
  demo-api-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
  demo-api-flyway:
    command: -url=jdbc:mysql://demo-api-db:3306/ -schemas=mydb -user=root -password=admin -connectRetries=60 migrate
    build:
      context: .
      dockerfile: flyway.dockerfile
    depends_on:
      - demo-api-db
  demo-api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - demo-api-db
      - demo-api-flyway
  demo-api-prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ${WORKDIR}/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - demo-api
  demo-api-grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      # - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=dashboard
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      # - ${WORKDIR}/grafana.ini:/etc/grafana/grafana.ini
      - ${WORKDIR}/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      - demo-api-prometheus
networks:
  default:
    external: true
    name: cicada-distributed-network
