apiVersion: v1
kind: Service
metadata:
  name: demo-api
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: demo-api
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api-db
spec:
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app: demo-api-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  labels:
    app: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - name: api
          image: cicadatesting/demo-api-app:local
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-db
  labels:
    app: demo-api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api-db
  template:
    metadata:
      labels:
        app: demo-api-db
    spec:
      containers:
        - name: db
          image: mysql
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
---
apiVersion: batch/v1
kind: Job
metadata:
  name: demo-api-flyway
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: flyway
        image: cicadatesting/demo-api-flyway:local
        imagePullPolicy: Never
        args:
          - "-url=jdbc:mysql://demo-api-db:3306/"
          - -schemas=mydb
          - -user=root
          - -password=admin
          - -connectRetries=60
          - migrate
